# =============================================================================
# C O P Y R I G H T
# -----------------------------------------------------------------------------
# Copyright (c) 2021 by Helmut Konrad Fahrendholz. All rights reserved.
# This file is property of Helmut Konrad Fahrendholz. Any unauthorized copy,
# use or distribution is an offensive act against international law and may
# be prosecuted under federal law. Its content is company confidential.
# =============================================================================

import utila

HEADLINES = utila.splitlines("""\
ABBILDUNGEN
ABBILDUNGSVERZEICHNIS
ABBREVIATIONS
ABBREVIATIONTABLE
ABKÜRZUNGEN
ABKÜRZUNGSVERZEICHNIS
ABSTRACT
ANHANG
ANHANGSVERZEICHNIS
APPENDIX
AUFBAU
AUFBAU UND GLIEDERUNG
AUSBLICK
BIBLIOGRAFIE
BIBLIOGRAPHIE
BIBLIOGRAPHY
CONCLUSIO
CONTENTS
DANKSAGUNG
DISKUSSION
DISKUSSION UND AUSBLICK
EIDESSTATTLICHE ERKLÄRUNG
EIDESSTATTLICHE VERSICHERUNG
EINFÜHRUNG
EINLEITUNG
ERGEBNIS
ERGEBNISSE
ERKLÄRUNG
FORSCHUNGSFRAGE
GRUNDLAGEN
INHALT
INHALTSVERZEICHNIS
INTERNETQUELLEN
INTRODUCTION
KURZFASSUNG
LITERATUR
LITERATURE
LITERATURVERZEICHNIS
LITERATUR- UND QUELLENVERZEICHNIS
MOTIVATION UND ZIELSETZUNG
PERSPEKTIVEN
QUELLEN
QUELLENVERZEICHNIS
REFERENCE
REFERENCES
SYMBOL
SYMBOLVERZEICHNIS
TABELLEN
TABELLENVERZEICHNIS
TABLE OF CONTENT
VERZEICHNIS DER LISTINGS
VORWORT
WEITERFÜHRENDE LITERATUR
ZEITSCHRIFTENARTIKEL
ZUSAMMENFASSUNG
ZUSAMMENFASSUNG & AUSBLICK
ZUSAMMENFASSUNG UND AUSBLICK
""")
